### ISSUE TITLE
Support Structured Logging

### ISSUE THREAD

**Issue by woorui** [yomorun/yomo#413]
### Summary 

Adding structured logging to Yomo.

Structured logging is the ability to output logs with machine-readable structure, typically key-value pairs, in addition to a human-readable message.

### Tasks

- [x] Implements logger that loads log config from the environment. #407
- [x] yomo/core pkg uses the logger. #410 
- [x] yomo pkg uses the logger. #411 
- [x] update examples. #412
